version: "3"
services:
  app:
    build:
      context: .
    expose:
      - "${PORT}"
    ports:
      - "80:${PORT}"
    environment:
      - PYTHON_ENV
      - PORT
    depends_on:
      - redis
  redis:
    image: redis:5.0.0
    ports:
      - "6379:6379"
